# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    admin.cathegorie:
        class: App\Admin\CathegorieAdmin
        arguments: [~, App\Entity\Cathegorie, App\Controller\CathegorieAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Cathegorie }
        public: true

    admin.article:
        class: App\Admin\ArticleAdmin
        arguments: [~, App\Entity\Article, App\Controller\ArticleAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Article }
        public: true

    admin.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, App\Controller\UserAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: User }
        public: true

    admin.comment:
        class: App\Admin\CommentAdmin
        arguments: [~, App\Entity\Comment, App\Controller\CommentAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Comment }
        public: true

    admin.recommandation_user:
        class: App\Admin\RecommandationUserAdmin
        arguments: [~, App\Entity\RecommandationUser, App\Controller\RecommandationUserAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: RecommandationUser }
        public: true

    admin.recommandation_cathegorie:
        class: App\Admin\RecommandationCathegorieAdmin
        arguments: [~, App\Entity\RecommandationCathegorie, App\Controller\RecommandationCathegorieAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: RecommandationCathegorie }
        public: true

    admin.recommandation_article:
        class: App\Admin\RecommandationArticleAdmin
        arguments: [~, App\Entity\RecommandationArticle, App\Controller\RecommandationArticleAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: RecommandationArticle }
        public: true
